const entityTypes = {
	SCENERY: "SCENERY",
	FLOOR: "FLOOR",
	ENEMY: "ENEMY",
	PLAYER: "PLAYER",
    POWERUP: "POWERUP"
}

const DEFAULTSTATE = "DEFAULTSTATE";
const WORLDGRAVITY = [0, 4];
const WORLDSIZE = [1366, 768];